// Run once from the project root:
//   cd ~/Desktop/quiz-it
//   node _speedquizzing_import/applyNearestWinsRewrite.mjs --dry-run   (preview, no writes)
//   node _speedquizzing_import/applyNearestWinsRewrite.mjs             (apply for real)
//
// Background: approveNearestWins.mjs bulk-approved all 439 speedquizzing_import
// nearest_wins rows, including 209 that were originally SpeedQuizzing PICTURE
// rounds - their question_text leans on an image ("this English woman", "these
// footballers") that was never imported. Quiz-It's nearest_wins round type is
// text-only by design (see the generation prompt in lib/quiz/questionGenerationCore.ts),
// so those 209 don't work as-is.
//
// nearest_wins_rewritten.csv (generated by hand/AI review, checked in alongside
// this script) has one row per affected question:
//   question_text_original, question_text_rewritten, answer, flag
// - question_text_rewritten is set (non-empty) for the 152 rows where the
//   answer's explanation named the subject clearly enough to rewrite the
//   question so it stands alone without an image.
// - flag is set (question_text_rewritten left blank) for the 57 rows where
//   the picture is genuinely load-bearing (counting objects in a photo, "which
//   minute is this movie still from", a song word-count where the song itself
//   is never named) - text alone can't save these.
//
// This script:
//   1. For the 152 rewritten rows: UPDATE question_bank.question_text to the
//      rewritten text, matched by exact question_text + question_type='nearest_wins'
//      + source='speedquizzing_import'.
//   2. For the 57 flagged rows: re-set needs_review=true and review_note to the
//      flag reason, so they stop being pickable until someone attaches a real
//      image pipeline or retires them.
//
// Scoped narrowly (question_type + source) so it can never touch a hand-written
// or AI-generated question. Matches by exact original question_text, so a row
// already edited/removed in question_bank since the CSV was generated is safely
// skipped (reported, not silently overwritten).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createClient } from "@supabase/supabase-js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, "..", ".env.local");
const CSV_PATH = path.join(__dirname, "nearest_wins_rewritten.csv");
const DRY_RUN = process.argv.includes("--dry-run");

function loadEnv() {
  const text = fs.readFileSync(ENV_PATH, "utf8");
  const env = {};
  for (const line of text.split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) env[m[1]] = m[2].trim();
  }
  return env;
}

function parseCSV(text) {
  const rows = [];
  let row = [], field = "", inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ",") { row.push(field); field = ""; }
      else if (c === "\r") { /* skip */ }
      else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
      else field += c;
    }
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  const header = rows.shift();
  return rows.filter(r => r.length === header.length).map(r => Object.fromEntries(header.map((h, i) => [h, r[i]])));
}

async function main() {
  const env = loadEnv();
  const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !supabaseKey) {
    console.error("Missing NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local");
    process.exit(1);
  }
  const supabase = createClient(supabaseUrl, supabaseKey);

  const csvText = fs.readFileSync(CSV_PATH, "utf8");
  const rows = parseCSV(csvText);
  const toRewrite = rows.filter(r => r.question_text_rewritten && r.question_text_rewritten.trim());
  const toFlag = rows.filter(r => !r.question_text_rewritten || !r.question_text_rewritten.trim());

  console.log(`${DRY_RUN ? "[DRY RUN] " : ""}Loaded ${rows.length} rows: ${toRewrite.length} to rewrite, ${toFlag.length} to re-flag.`);

  let rewritten = 0, rewriteMisses = 0, flagged = 0, flagMisses = 0;

  for (const r of toRewrite) {
    if (DRY_RUN) { rewritten++; continue; }
    const { error, count } = await supabase.from("question_bank")
      .update({ question_text: r.question_text_rewritten }, { count: "exact" })
      .eq("question_type", "nearest_wins")
      .eq("source", "speedquizzing_import")
      .eq("question_text", r.question_text_original);
    if (error) { console.error(`Rewrite failed for "${r.question_text_original.slice(0, 60)}...": ${error.message}`); rewriteMisses++; continue; }
    if (!count) { console.warn(`No matching row (already edited/removed?) for "${r.question_text_original.slice(0, 60)}..."`); rewriteMisses++; continue; }
    rewritten += count;
  }

  for (const r of toFlag) {
    const note = `SpeedQuizzing import: original was a picture-round question, no image available, and text alone can't stand in for it (${r.flag || "unresolvable without the image"}).`;
    if (DRY_RUN) { flagged++; continue; }
    const { error, count } = await supabase.from("question_bank")
      .update({ needs_review: true, review_note: note }, { count: "exact" })
      .eq("question_type", "nearest_wins")
      .eq("source", "speedquizzing_import")
      .eq("question_text", r.question_text_original);
    if (error) { console.error(`Flag failed for "${r.question_text_original.slice(0, 60)}...": ${error.message}`); flagMisses++; continue; }
    if (!count) { console.warn(`No matching row (already edited/removed?) for "${r.question_text_original.slice(0, 60)}..."`); flagMisses++; continue; }
    flagged += count;
  }

  console.log(`${DRY_RUN ? "[DRY RUN] Would rewrite" : "Rewrote"} ${rewritten} question(s)${rewriteMisses ? ` (${rewriteMisses} not found)` : ""}.`);
  console.log(`${DRY_RUN ? "[DRY RUN] Would re-flag" : "Re-flagged"} ${flagged} question(s) as needs_review${flagMisses ? ` (${flagMisses} not found)` : ""}.`);
  if (DRY_RUN) console.log("Nothing was written. Re-run without --dry-run to apply.");
}

main().catch(e => { console.error(e); process.exit(1); });
