"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { ImageUploader } from "@/components/ImageUploader";
import { HostButton, HostInput, HostLabel, HostLoading, HostShell } from "@/components/fable/HostConsole";

const BG="radial-gradient(ellipse 55% 45% at 50% 45%, rgba(190,38,193,0.12), transparent 70%), #0A0118";
const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
type Venue={id:string;day_of_week:number;venue_name:string;venue_logo_url:string|null;hero_image_url:string|null;gallery_images:string[];address:string|null;google_maps_url:string|null;contact_name:string|null;contact_email:string|null;contact_phone:string|null;website:string|null;social_links:Record<string,string>;default_host_id:string|null;default_host_name:string|null;default_quiz_id:string|null;default_quiz_day:number|null;default_start_time:string|null;default_end_time:string|null;food_offers:string|null;drink_offers:string|null;happy_hour:string|null;prize_information:string|null;sponsors:string[];brand_colours:Record<string,string>;display_slides:string[];display_adverts:string[];default_music_pack:string|null;notes:string|null;active:boolean};
type FormState={venue_name:string;venue_logo_url:string;hero_image_url:string;gallery_images:string[];address:string;google_maps_url:string;contact_name:string;contact_email:string;contact_phone:string;website:string;social_links:string;default_host_id:string;default_host_name:string;default_quiz_id:string;default_quiz_day:string;default_start_time:string;default_end_time:string;food_offers:string;drink_offers:string;happy_hour:string;prize_information:string;sponsors:string;brand_colours:string;display_slides:string;display_adverts:string;default_music_pack:string;notes:string;active:boolean};
const empty:FormState={venue_name:"",venue_logo_url:"",hero_image_url:"",gallery_images:[],address:"",google_maps_url:"",contact_name:"",contact_email:"",contact_phone:"",website:"",social_links:"",default_host_id:"",default_host_name:"",default_quiz_id:"",default_quiz_day:"",default_start_time:"19:30",default_end_time:"21:30",food_offers:"",drink_offers:"",happy_hour:"",prize_information:"",sponsors:"",brand_colours:"",display_slides:"",display_adverts:"",default_music_pack:"",notes:"",active:true};
const textArea={width:"100%",padding:"11px 14px",borderRadius:12,background:"#150A2E",color:"#fff",border:"1px solid #2E1A52",font:"500 13px Inter"} as const;
const split=(value:string)=>value.split(",").map(v=>v.trim()).filter(Boolean);
const pairs=(value:string)=>Object.fromEntries(split(value).map(item=>{const [key,...rest]=item.split(":");return [key.trim(),rest.join(":").trim()]}).filter(([,value])=>value));
const pairText=(value:Record<string,string>|null)=>Object.entries(value||{}).map(([key,item])=>`${key}: ${item}`).join(", ");
function toForm(venue:Venue):FormState{return{venue_name:venue.venue_name||"",venue_logo_url:venue.venue_logo_url||"",hero_image_url:venue.hero_image_url||"",gallery_images:venue.gallery_images||[],address:venue.address||"",google_maps_url:venue.google_maps_url||"",contact_name:venue.contact_name||"",contact_email:venue.contact_email||"",contact_phone:venue.contact_phone||"",website:venue.website||"",social_links:pairText(venue.social_links),default_host_id:venue.default_host_id||"",default_host_name:venue.default_host_name||"",default_quiz_id:venue.default_quiz_id||"",default_quiz_day:venue.default_quiz_day==null?"":String(venue.default_quiz_day),default_start_time:venue.default_start_time?.slice(0,5)||"",default_end_time:venue.default_end_time?.slice(0,5)||"",food_offers:venue.food_offers||"",drink_offers:venue.drink_offers||"",happy_hour:venue.happy_hour||"",prize_information:venue.prize_information||"",sponsors:(venue.sponsors||[]).join(", "),brand_colours:pairText(venue.brand_colours),display_slides:(venue.display_slides||[]).join(", "),display_adverts:(venue.display_adverts||[]).join(", "),default_music_pack:venue.default_music_pack||"",notes:venue.notes||"",active:venue.active};}

export default function VenueManagerPage(){
  const [venues,setVenues]=useState<Venue[]>([]);const [quizzes,setQuizzes]=useState<{id:string;name:string}[]>([]);const [host,setHost]=useState({id:"",name:"Current host"});const [form,setForm]=useState<FormState>(empty);const [editing,setEditing]=useState<string|null>(null);const [section,setSection]=useState("profile");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{const supabase=createSupabaseBrowserClient();const[{data:venueData,error:venueError},{data:quizData},{data:userData}]=await Promise.all([supabase.from("venues").select("*").order("venue_name"),supabase.from("quizzes").select("id,name").eq("archived",false).order("name"),supabase.auth.getUser()]);setVenues((venueData||[]) as Venue[]);setQuizzes(quizData||[]);const user=userData.user;setHost({id:user?.id||"",name:String(user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email||"Current host")});if(venueError)setError(venueError.message);setLoading(false);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  function set<K extends keyof FormState>(key:K,value:FormState[K]){setForm(current=>({...current,[key]:value}));}
  function edit(venue:Venue){setEditing(venue.id);setForm(toForm(venue));setSection("profile");window.scrollTo({top:0,behavior:"smooth"});}
  function clear(){setEditing(null);setForm({...empty,default_host_id:host.id,default_host_name:host.name});setSection("profile");setError("");}
  async function save(){if(!form.venue_name.trim())return;setSaving(true);setError("");const payload={venue_name:form.venue_name.trim(),venue_logo_url:form.venue_logo_url||null,hero_image_url:form.hero_image_url||null,gallery_images:form.gallery_images,address:form.address||null,google_maps_url:form.google_maps_url||null,contact_name:form.contact_name||null,contact_email:form.contact_email||null,contact_phone:form.contact_phone||null,website:form.website||null,social_links:pairs(form.social_links),default_host_id:form.default_host_id||host.id,default_host_name:form.default_host_name||null,default_quiz_id:form.default_quiz_id||null,default_quiz_day:form.default_quiz_day===""?null:Number(form.default_quiz_day),default_start_time:form.default_start_time||null,default_end_time:form.default_end_time||null,food_offers:form.food_offers||null,drink_offers:form.drink_offers||null,happy_hour:form.happy_hour||null,prize_information:form.prize_information||null,sponsors:split(form.sponsors),brand_colours:pairs(form.brand_colours),display_slides:split(form.display_slides),display_adverts:split(form.display_adverts),default_music_pack:form.default_music_pack||null,notes:form.notes||null,active:form.active,updated_at:new Date().toISOString()};const supabase=createSupabaseBrowserClient();
    const result=editing
      ?await supabase.from("venues").update(payload).eq("id",editing).select().single()
      :await supabase.from("venues").insert({...payload,day_of_week:venues.reduce((max,v)=>Math.max(max,v.day_of_week),-1)+1}).select().single();
    if(result.error)setError(result.error.message);
    else{
      // Stay on the venue that was just saved (whether newly created or an
      // existing one) instead of wiping the form back to a blank "New
      // Venue" draft - a save should never discard your place, only "New
      // Venue" or picking a different venue from the list should.
      setEditing(result.data.id);
      setForm(toForm(result.data as Venue));
      await load();
    }
    setSaving(false);}
  if(loading)return <HostShell><main style={{minHeight:"100vh",background:BG,display:"grid",placeItems:"center"}}><HostLoading title="Venue Manager" note="Loading permanent venue profiles…"/></main></HostShell>;
  const sections=["profile","schedule","experience","media","notes"];
  return <HostShell><main className="qi-bo-page"><header className="qi-bo-pagehead"><div><p>Business profiles</p><h1>Venues</h1><span>Everything Quiz-It should remember about each venue.</span></div><div style={{display:"flex",gap:12}}><Link className="fbh-btn" href="/host/events">Calendar</Link><button className="fbh-btn pri" onClick={clear}>New Venue</button></div></header>
    <div className="qi-bo-venue-layout"><aside className="qi-bo-venue-list"><h2>Venue profiles</h2>{venues.map(venue=><button key={venue.id} onClick={()=>edit(venue)} aria-pressed={editing===venue.id}><span className="qi-bo-venue-logo">{venue.venue_logo_url?<Image unoptimized src={venue.venue_logo_url} width={64} height={64} alt=""/>:venue.venue_name.slice(0,2).toUpperCase()}</span><span><strong>{venue.venue_name}</strong><small>{venue.default_quiz_day==null?"Schedule not set":`${DAYS[venue.default_quiz_day]} · ${venue.default_start_time?.slice(0,5)||"Time needed"}`}</small></span><i>{venue.active?"Active":"Inactive"}</i></button>)}</aside>
      <section className="qi-bo-venue-profile"><header><div><p>{editing?"Venue profile":"New venue"}</p><input value={form.venue_name} onChange={e=>set("venue_name",e.target.value)} placeholder="Name this venue" aria-label="Venue name" style={{background:"transparent",border:"none",borderBottom:"2px solid "+(form.venue_name.trim()?"transparent":"#FFC533"),color:"#fff",font:"700 28px Inter",padding:"2px 0",width:"100%",maxWidth:420}}/></div><span className={form.active?"qi-bo-status live":"qi-bo-status cancelled"}>{form.active?"Active":"Inactive"}</span></header>
        <nav className="qi-bo-profile-tabs" aria-label="Venue profile sections">{sections.map(item=><button key={item} aria-pressed={section===item} onClick={()=>setSection(item)}>{item}</button>)}</nav>
        {section==="profile"&&<div className="qi-bo-profile-section"><h3>Business profile</h3><p>The identity and contact details used throughout the Back Office.</p><HostLabel>Venue Name</HostLabel><HostInput value={form.venue_name} onChange={e=>set("venue_name",e.target.value)}/><HostLabel>Logo</HostLabel><ImageUploader currentUrl={form.venue_logo_url||null} onUploaded={url=>set("venue_logo_url",url)}/><div className="qi-bo-form-grid"><Field label="Address" value={form.address} set={v=>set("address",v)}/><Field label="Google Maps Link" value={form.google_maps_url} set={v=>set("google_maps_url",v)}/><Field label="Contact Name" value={form.contact_name} set={v=>set("contact_name",v)}/><Field label="Contact Email" type="email" value={form.contact_email} set={v=>set("contact_email",v)}/><Field label="Contact Phone" value={form.contact_phone} set={v=>set("contact_phone",v)}/><Field label="Website" value={form.website} set={v=>set("website",v)}/></div><HostLabel>Facebook and Instagram</HostLabel><HostInput value={form.social_links} onChange={e=>set("social_links",e.target.value)} placeholder="instagram: URL, facebook: URL"/></div>}
        {section==="schedule"&&<div className="qi-bo-profile-section"><h3>Quiz defaults</h3><p>Choose once. New calendar events inherit these details automatically.</p><div className="qi-bo-form-grid"><Field label="Default Host" value={form.default_host_name} set={v=>set("default_host_name",v)} placeholder={host.name}/><div><HostLabel>Default Quiz Plan</HostLabel><select value={form.default_quiz_id} onChange={e=>set("default_quiz_id",e.target.value)}><option value="">Choose a Quiz Plan</option>{quizzes.map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></div><div><HostLabel>Default Quiz Day</HostLabel><select value={form.default_quiz_day} onChange={e=>set("default_quiz_day",e.target.value)}><option value="">Choose a day</option>{DAYS.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></div><Field label="Music Pack" value={form.default_music_pack} set={v=>set("default_music_pack",v)}/><Field label="Start Time" type="time" value={form.default_start_time} set={v=>set("default_start_time",v)}/><Field label="End Time" type="time" value={form.default_end_time} set={v=>set("default_end_time",v)}/></div></div>}
        {section==="experience"&&<div className="qi-bo-profile-section"><h3>Venue experience</h3><p>Commercial content inherited by every event at this venue.</p>{[["food_offers","Food Offers"],["drink_offers","Drink Offers"],["happy_hour","Happy Hour"],["prize_information","Prize Information"],["sponsors","Sponsors"],["brand_colours","Brand Colours"]].map(([key,label])=><Area key={key} label={label} value={String(form[key as keyof FormState]||"")} setValue={v=>set(key as keyof FormState,v as never)}/>)}</div>}
        {section==="media"&&<div className="qi-bo-profile-section"><h3>Display media</h3><p>Visual assets preloaded for the venue experience.</p><HostLabel>Hero Image</HostLabel><ImageUploader currentUrl={form.hero_image_url||null} onUploaded={url=>set("hero_image_url",url)}/><HostLabel>Gallery</HostLabel><ImageUploader currentUrl={null} onUploaded={url=>set("gallery_images",[...form.gallery_images,url])}/><div className="qi-bo-gallery">{form.gallery_images.map(url=><div key={url}><Image unoptimized fill sizes="180px" src={url} alt="Venue gallery"/><button onClick={()=>set("gallery_images",form.gallery_images.filter(item=>item!==url))} aria-label="Remove gallery image">×</button></div>)}</div><Area label="Display Slides" value={form.display_slides} setValue={v=>set("display_slides",v)}/><Area label="Display Adverts" value={form.display_adverts} setValue={v=>set("display_adverts",v)}/></div>}
        {section==="notes"&&<div className="qi-bo-profile-section"><h3>Internal notes</h3><p>Private operational information for hosts and administrators.</p><Area label="Notes" value={form.notes} setValue={v=>set("notes",v)} rows={8}/><div className="qi-bo-active-row"><div><strong>Venue availability</strong><span>{form.active?"Available when scheduling events":"Hidden from new event scheduling"}</span></div><button className="fbh-btn" onClick={()=>set("active",!form.active)}>{form.active?"Deactivate venue":"Activate venue"}</button></div></div>}
        {error&&<div className="qi-bo-alert" role="alert">{error}</div>}<footer><span>{!form.venue_name.trim()?<span style={{color:"#FFC533"}}>Enter a Venue Name on the Profile tab to save.</span>:editing?"Changes apply to future events. Live sessions keep their snapshot.":"Complete the profile at your own pace."}</span><HostButton variant="pri" big onClick={()=>{if(!form.venue_name.trim()){setSection("profile");return;}save();}} disabled={saving}>{saving?"Saving…":editing?"Save venue":"Create venue"}</HostButton></footer>
      </section></div></main></HostShell>;
}

function Field({label,value,set,type="text",placeholder}:{label:string;value:string;set:(value:string)=>void;type?:string;placeholder?:string}){return <div><HostLabel>{label}</HostLabel><HostInput type={type} value={value} placeholder={placeholder} onChange={event=>set(event.target.value)}/></div>}
function Area({label,value,setValue,rows=3}:{label:string;value:string;setValue:(value:string)=>void;rows?:number}){return <div><HostLabel>{label}</HostLabel><textarea style={textArea} rows={rows} value={value} onChange={event=>setValue(event.target.value)}/></div>}
