"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { ImageUploader } from "@/components/ImageUploader";
import { HostButton, HostInput, HostLabel, HostLoading, HostShell, TopSpacer } from "@/components/fable/HostConsole";

const BG="radial-gradient(ellipse 55% 45% at 50% 45%, rgba(190,38,193,0.12), transparent 70%), #0A0118";
const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
type Venue={id:string;day_of_week:number;venue_name:string;venue_logo_url:string|null;hero_image_url:string|null;gallery_images:string[];address:string|null;google_maps_url:string|null;contact_name:string|null;contact_email:string|null;contact_phone:string|null;website:string|null;social_links:Record<string,string>;default_host_id:string|null;default_host_name:string|null;default_quiz_id:string|null;default_quiz_day:number|null;default_start_time:string|null;default_end_time:string|null;food_offers:string|null;drink_offers:string|null;happy_hour:string|null;prize_information:string|null;sponsors:string[];brand_colours:Record<string,string>;display_slides:string[];display_adverts:string[];default_music_pack:string|null;notes:string|null;active:boolean};
type FormState={venue_name:string;venue_logo_url:string;hero_image_url:string;gallery_images:string[];address:string;google_maps_url:string;contact_name:string;contact_email:string;contact_phone:string;website:string;social_links:string;default_host_id:string;default_host_name:string;default_quiz_id:string;default_quiz_day:string;default_start_time:string;default_end_time:string;food_offers:string;drink_offers:string;happy_hour:string;prize_information:string;sponsors:string;brand_colours:string;display_slides:string;display_adverts:string;default_music_pack:string;notes:string;active:boolean};
const empty:FormState={venue_name:"",venue_logo_url:"",hero_image_url:"",gallery_images:[],address:"",google_maps_url:"",contact_name:"",contact_email:"",contact_phone:"",website:"",social_links:"",default_host_id:"",default_host_name:"",default_quiz_id:"",default_quiz_day:"",default_start_time:"19:30",default_end_time:"21:30",food_offers:"",drink_offers:"",happy_hour:"",prize_information:"",sponsors:"",brand_colours:"",display_slides:"",display_adverts:"",default_music_pack:"",notes:"",active:true};
const textArea={width:"100%",padding:"11px 14px",borderRadius:12,background:"#150A2E",color:"#fff",border:"1px solid #2E1A52",font:"500 13px Inter"} as const;
const split=(value:string)=>value.split(",").map(v=>v.trim()).filter(Boolean);
const pairs=(value:string)=>Object.fromEntries(split(value).map(item=>{const [key,...rest]=item.split(":");return [key.trim(),rest.join(":").trim()]}).filter(([,value])=>value));
const pairText=(value:Record<string,string>|null)=>Object.entries(value||{}).map(([key,item])=>`${key}: ${item}`).join(", ");
function toForm(venue:Venue):FormState{return{venue_name:venue.venue_name||"",venue_logo_url:venue.venue_logo_url||"",hero_image_url:venue.hero_image_url||"",gallery_images:venue.gallery_images||[],address:venue.address||"",google_maps_url:venue.google_maps_url||"",contact_name:venue.contact_name||"",contact_email:venue.contact_email||"",contact_phone:venue.contact_phone||"",website:venue.website||"",social_links:pairText(venue.social_links),default_host_id:venue.default_host_id||"",default_host_name:venue.default_host_name||"",default_quiz_id:venue.default_quiz_id||"",default_quiz_day:venue.default_quiz_day==null?"":String(venue.default_quiz_day),default_start_time:venue.default_start_time?.slice(0,5)||"",default_end_time:venue.default_end_time?.slice(0,5)||"",food_offers:venue.food_offers||"",drink_offers:venue.drink_offers||"",happy_hour:venue.happy_hour||"",prize_information:venue.prize_information||"",sponsors:(venue.sponsors||[]).join(", "),brand_colours:pairText(venue.brand_colours),display_slides:(venue.display_slides||[]).join(", "),display_adverts:(venue.display_adverts||[]).join(", "),default_music_pack:venue.default_music_pack||"",notes:venue.notes||"",active:venue.active};}

export default function VenueManagerPage(){
  const [venues,setVenues]=useState<Venue[]>([]);const [quizzes,setQuizzes]=useState<{id:string;name:string}[]>([]);const [host,setHost]=useState({id:"",name:"Current host"});const [form,setForm]=useState<FormState>(empty);const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{const supabase=createSupabaseBrowserClient();const[{data:venueData,error:venueError},{data:quizData},{data:userData}]=await Promise.all([supabase.from("venues").select("*").order("venue_name"),supabase.from("quizzes").select("id,name").eq("archived",false).order("name"),supabase.auth.getUser()]);setVenues((venueData||[]) as Venue[]);setQuizzes(quizData||[]);const user=userData.user;setHost({id:user?.id||"",name:String(user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email||"Current host")});if(venueError)setError(venueError.message);setLoading(false);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  function set<K extends keyof FormState>(key:K,value:FormState[K]){setForm(current=>({...current,[key]:value}));}
  function edit(venue:Venue){setEditing(venue.id);setForm(toForm(venue));window.scrollTo({top:0,behavior:"smooth"});}
  function clear(){setEditing(null);setForm({...empty,default_host_id:host.id,default_host_name:host.name});setError("");}
  async function save(){if(!form.venue_name.trim())return;setSaving(true);setError("");const payload={venue_name:form.venue_name.trim(),venue_logo_url:form.venue_logo_url||null,hero_image_url:form.hero_image_url||null,gallery_images:form.gallery_images,address:form.address||null,google_maps_url:form.google_maps_url||null,contact_name:form.contact_name||null,contact_email:form.contact_email||null,contact_phone:form.contact_phone||null,website:form.website||null,social_links:pairs(form.social_links),default_host_id:form.default_host_id||host.id,default_host_name:form.default_host_name||null,default_quiz_id:form.default_quiz_id||null,default_quiz_day:form.default_quiz_day===""?null:Number(form.default_quiz_day),default_start_time:form.default_start_time||null,default_end_time:form.default_end_time||null,food_offers:form.food_offers||null,drink_offers:form.drink_offers||null,happy_hour:form.happy_hour||null,prize_information:form.prize_information||null,sponsors:split(form.sponsors),brand_colours:pairs(form.brand_colours),display_slides:split(form.display_slides),display_adverts:split(form.display_adverts),default_music_pack:form.default_music_pack||null,notes:form.notes||null,active:form.active,updated_at:new Date().toISOString()};const supabase=createSupabaseBrowserClient();const result=editing?await supabase.from("venues").update(payload).eq("id",editing):await supabase.from("venues").insert({...payload,day_of_week:venues.reduce((max,v)=>Math.max(max,v.day_of_week),-1)+1});if(result.error)setError(result.error.message);else{clear();await load();}setSaving(false);}
  if(loading)return <HostShell><main style={{minHeight:"100vh",background:BG,display:"grid",placeItems:"center"}}><HostLoading title="Venue Manager" note="Loading permanent venue profiles…"/></main></HostShell>;
  return <HostShell><main style={{minHeight:"100vh",background:BG,color:"#fff",padding:"24px 32px"}}><header className="fbh-top"><span className="fbh-wm"><span className="q">QUIZ-</span>IT</span><span className="fbh-bc">Venue Manager</span><TopSpacer/><Link className="fbh-btn" href="/host/events">Calendar</Link><button className="fbh-btn pri" onClick={clear}>New Venue</button></header>
    <div className="qi-quiz-builder-grid" style={{marginTop:18,alignItems:"start"}}><section className="fbh-panel"><div className="fbh-lbl">{editing?"Edit Venue":"New Venue"}</div><HostLabel>Venue Name</HostLabel><HostInput value={form.venue_name} onChange={e=>set("venue_name",e.target.value)}/><HostLabel>Logo</HostLabel><ImageUploader currentUrl={form.venue_logo_url||null} onUploaded={url=>set("venue_logo_url",url)}/><HostLabel>Hero Image</HostLabel><ImageUploader currentUrl={form.hero_image_url||null} onUploaded={url=>set("hero_image_url",url)}/><HostLabel>Gallery Images</HostLabel><ImageUploader currentUrl={null} onUploaded={url=>set("gallery_images",[...form.gallery_images,url])}/>{form.gallery_images.length>0&&<div style={{fontSize:12,color:"#B9A8D9",marginBottom:12}}>{form.gallery_images.length} gallery image{form.gallery_images.length===1?"":"s"} saved</div>}
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><div><HostLabel>Address</HostLabel><HostInput value={form.address} onChange={e=>set("address",e.target.value)}/></div><div><HostLabel>Google Maps Link</HostLabel><HostInput value={form.google_maps_url} onChange={e=>set("google_maps_url",e.target.value)}/></div><div><HostLabel>Contact Name</HostLabel><HostInput value={form.contact_name} onChange={e=>set("contact_name",e.target.value)}/></div><div><HostLabel>Contact Email</HostLabel><HostInput type="email" value={form.contact_email} onChange={e=>set("contact_email",e.target.value)}/></div><div><HostLabel>Contact Phone</HostLabel><HostInput value={form.contact_phone} onChange={e=>set("contact_phone",e.target.value)}/></div><div><HostLabel>Website</HostLabel><HostInput value={form.website} onChange={e=>set("website",e.target.value)}/></div></div><HostLabel>Social Links</HostLabel><HostInput value={form.social_links} onChange={e=>set("social_links",e.target.value)} placeholder="instagram: URL, facebook: URL"/>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><div><HostLabel>Default Host</HostLabel><HostInput value={form.default_host_name} onChange={e=>set("default_host_name",e.target.value)} placeholder={host.name}/></div><div><HostLabel>Default Quiz Plan</HostLabel><select className="fbh-input" style={{width:"100%"}} value={form.default_quiz_id} onChange={e=>set("default_quiz_id",e.target.value)}><option value="">No default</option>{quizzes.map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></div><div><HostLabel>Default Quiz Day</HostLabel><select className="fbh-input" style={{width:"100%"}} value={form.default_quiz_day} onChange={e=>set("default_quiz_day",e.target.value)}><option value="">No default</option>{DAYS.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></div><div><HostLabel>Music Pack</HostLabel><HostInput value={form.default_music_pack} onChange={e=>set("default_music_pack",e.target.value)}/></div><div><HostLabel>Start Time</HostLabel><HostInput type="time" value={form.default_start_time} onChange={e=>set("default_start_time",e.target.value)}/></div><div><HostLabel>End Time</HostLabel><HostInput type="time" value={form.default_end_time} onChange={e=>set("default_end_time",e.target.value)}/></div></div>
      {[['food_offers','Food Offers'],['drink_offers','Drink Offers'],['happy_hour','Happy Hour'],['prize_information','Prize Information'],['sponsors','Sponsors'],['brand_colours','Brand Colours'],['display_slides','Display Slides'],['display_adverts','Display Adverts'],['notes','Internal Notes']] .map(([key,label])=><div key={key}><HostLabel>{label}</HostLabel><textarea style={textArea} rows={key==='notes'?4:2} value={String(form[key as keyof FormState]||"")} onChange={e=>set(key as keyof FormState,e.target.value as never)} placeholder={key==='brand_colours'?"primary: #BE26C1, background: #0A0118":key.includes('display')?"Comma-separated media URLs":undefined}/></div>)}
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginTop:12}}><span>Venue is {form.active?"active":"inactive"}</span><button className="fbh-btn" onClick={()=>set("active",!form.active)}>{form.active?"DEACTIVATE":"ACTIVATE"}</button></div>{error&&<div role="alert" style={{color:"#FF7070",marginTop:10}}>{error}</div>}<HostButton variant="pri" big onClick={save} disabled={saving||!form.venue_name.trim()} style={{width:"100%",marginTop:14}}>{saving?"SAVING…":editing?"SAVE VENUE":"CREATE VENUE"}</HostButton></section>
      <section><div className="fbh-lbl">Permanent Venues</div>{venues.map(venue=><article className="fbh-panel" key={venue.id} style={{opacity:venue.active?1:.55,display:"flex",gap:14,alignItems:"center"}}>{venue.venue_logo_url?<Image unoptimized src={venue.venue_logo_url} width={58} height={58} alt="" style={{width:58,height:58,borderRadius:12,objectFit:"cover"}}/>:<div style={{width:58,height:58,borderRadius:12,background:"#150A2E"}}/>}<div style={{flex:1}}><strong style={{fontSize:17}}>{venue.venue_name}</strong><div style={{color:"#B9A8D9",fontSize:12,marginTop:5}}>{venue.address||"No address"}</div><div style={{color:"#6B5A8E",fontSize:11,marginTop:4}}>{venue.default_quiz_day==null?"No default day":DAYS[venue.default_quiz_day]} · {venue.default_start_time?.slice(0,5)||"No start time"}</div></div><HostButton onClick={()=>edit(venue)}>EDIT</HostButton></article>)}</section></div>
  </main></HostShell>;
}
